// <auto-generated />
namespace TMS_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class islemememem223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(islemememem223));
        
        string IMigrationMetadata.Id
        {
            get { return "202005231522364_islemememem223"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
