namespace TMS_API.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class oslemm : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Departments", "ManagerId", "dbo.StaffMembers");
            DropForeignKey("dbo.InternalNotes", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.Tickets", "UserId", "dbo.Users");
            DropForeignKey("dbo.TicketEventsHistories", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.TicketThreadMessages", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.InternalNotes", "AuthorId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "AssignedStaffId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "CreatorStaffId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "EditorStaffId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "LastRespondentId", "dbo.StaffMembers");
            DropForeignKey("dbo.StaffLogs", "StaffMemberId", "dbo.StaffMembers");
            DropForeignKey("dbo.TicketEventsHistories", "DoerId", "dbo.StaffMembers");
            DropForeignKey("dbo.TicketThreadMessages", "StaffAuthorId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "HelpTopicId", "dbo.HelpTopics");
            DropForeignKey("dbo.Tickets", "LicenseId", "dbo.Licenses");
            DropForeignKey("dbo.Licenses", "UserID", "dbo.Users");
            DropForeignKey("dbo.TicketThreadMessages", "UserAuthorId", "dbo.Users");
            DropIndex("dbo.Departments", new[] { "ManagerId" });
            DropIndex("dbo.InternalNotes", new[] { "TicketId" });
            DropIndex("dbo.InternalNotes", new[] { "AuthorId" });
            DropIndex("dbo.Tickets", new[] { "UserId" });
            DropIndex("dbo.Tickets", new[] { "LicenseId" });
            DropIndex("dbo.Tickets", new[] { "AssignedStaffId" });
            DropIndex("dbo.Tickets", new[] { "LastRespondentId" });
            DropIndex("dbo.Tickets", new[] { "EditorStaffId" });
            DropIndex("dbo.Tickets", new[] { "HelpTopicId" });
            DropIndex("dbo.Tickets", new[] { "CreatorStaffId" });
            DropIndex("dbo.Licenses", new[] { "UserID" });
            DropIndex("dbo.StaffLogs", new[] { "StaffMemberId" });
            DropIndex("dbo.TicketEventsHistories", new[] { "TicketId" });
            DropIndex("dbo.TicketEventsHistories", new[] { "DoerId" });
            DropIndex("dbo.TicketThreadMessages", new[] { "TicketId" });
            DropIndex("dbo.TicketThreadMessages", new[] { "StaffAuthorId" });
            DropIndex("dbo.TicketThreadMessages", new[] { "UserAuthorId" });
            DropPrimaryKey("dbo.Departments");
            DropPrimaryKey("dbo.StaffMembers");
            DropPrimaryKey("dbo.HelpTopics");
            DropPrimaryKey("dbo.InternalNotes");
            DropPrimaryKey("dbo.Licenses");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.StaffGroups");
            DropPrimaryKey("dbo.StaffLogs");
            DropPrimaryKey("dbo.TicketEventsHistories");
            DropPrimaryKey("dbo.TicketThreadMessages");
            DropPrimaryKey("dbo.TMS_Settings");
            AlterColumn("dbo.Departments", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Departments", "ManagerId", c => c.Guid());
            AlterColumn("dbo.StaffMembers", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.StaffMembers", "StaffGroupId", c => c.Guid());
            AlterColumn("dbo.StaffMembers", "DepartmentId", c => c.Guid());
            AlterColumn("dbo.HelpTopics", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.InternalNotes", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.InternalNotes", "TicketId", c => c.Guid());
            AlterColumn("dbo.InternalNotes", "AuthorId", c => c.Guid());
            AlterColumn("dbo.Tickets", "UserId", c => c.Guid());
            AlterColumn("dbo.Tickets", "LicenseId", c => c.Guid());
            AlterColumn("dbo.Tickets", "AssignedStaffId", c => c.Guid());
            AlterColumn("dbo.Tickets", "LastRespondentId", c => c.Guid());
            AlterColumn("dbo.Tickets", "EditorStaffId", c => c.Guid());
            AlterColumn("dbo.Tickets", "HelpTopicId", c => c.Guid());
            AlterColumn("dbo.Tickets", "CreatorStaffId", c => c.Guid());
            AlterColumn("dbo.Licenses", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Licenses", "CustomerID", c => c.Guid());
            AlterColumn("dbo.Licenses", "UserID", c => c.Guid());
            AlterColumn("dbo.Users", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Users", "SupervisorId", c => c.Guid());
            AlterColumn("dbo.Users", "CustomerId", c => c.Guid());
            AlterColumn("dbo.StaffGroups", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.StaffLogs", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.StaffLogs", "StaffMemberId", c => c.Guid());
            AlterColumn("dbo.TicketEventsHistories", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.TicketEventsHistories", "TicketId", c => c.Guid());
            AlterColumn("dbo.TicketEventsHistories", "DoerId", c => c.Guid());
            AlterColumn("dbo.TicketThreadMessages", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.TicketThreadMessages", "TicketId", c => c.Guid());
            AlterColumn("dbo.TicketThreadMessages", "StaffAuthorId", c => c.Guid());
            AlterColumn("dbo.TicketThreadMessages", "UserAuthorId", c => c.Guid());
            AlterColumn("dbo.TMS_Settings", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.Departments", "Id");
            AddPrimaryKey("dbo.StaffMembers", "Id");
            AddPrimaryKey("dbo.HelpTopics", "Id");
            AddPrimaryKey("dbo.InternalNotes", "Id");
            AddPrimaryKey("dbo.Licenses", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.StaffGroups", "Id");
            AddPrimaryKey("dbo.StaffLogs", "Id");
            AddPrimaryKey("dbo.TicketEventsHistories", "Id");
            AddPrimaryKey("dbo.TicketThreadMessages", "Id");
            AddPrimaryKey("dbo.TMS_Settings", "Id");
            CreateIndex("dbo.Departments", "ManagerId");
            CreateIndex("dbo.InternalNotes", "TicketId");
            CreateIndex("dbo.InternalNotes", "AuthorId");
            CreateIndex("dbo.Tickets", "UserId");
            CreateIndex("dbo.Tickets", "LicenseId");
            CreateIndex("dbo.Tickets", "AssignedStaffId");
            CreateIndex("dbo.Tickets", "LastRespondentId");
            CreateIndex("dbo.Tickets", "EditorStaffId");
            CreateIndex("dbo.Tickets", "HelpTopicId");
            CreateIndex("dbo.Tickets", "CreatorStaffId");
            CreateIndex("dbo.Licenses", "UserID");
            CreateIndex("dbo.StaffLogs", "StaffMemberId");
            CreateIndex("dbo.TicketEventsHistories", "TicketId");
            CreateIndex("dbo.TicketEventsHistories", "DoerId");
            CreateIndex("dbo.TicketThreadMessages", "TicketId");
            CreateIndex("dbo.TicketThreadMessages", "StaffAuthorId");
            CreateIndex("dbo.TicketThreadMessages", "UserAuthorId");
            AddForeignKey("dbo.Departments", "ManagerId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.InternalNotes", "TicketId", "dbo.Tickets", "Id");
            AddForeignKey("dbo.Tickets", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TicketEventsHistories", "TicketId", "dbo.Tickets", "Id");
            AddForeignKey("dbo.TicketThreadMessages", "TicketId", "dbo.Tickets", "Id");
            AddForeignKey("dbo.InternalNotes", "AuthorId", "dbo.StaffMembers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tickets", "AssignedStaffId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.Tickets", "CreatorStaffId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.Tickets", "EditorStaffId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.Tickets", "LastRespondentId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.StaffLogs", "StaffMemberId", "dbo.StaffMembers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TicketEventsHistories", "DoerId", "dbo.StaffMembers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TicketThreadMessages", "StaffAuthorId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.Tickets", "HelpTopicId", "dbo.HelpTopics", "Id");
            AddForeignKey("dbo.Tickets", "LicenseId", "dbo.Licenses", "Id");
            AddForeignKey("dbo.Licenses", "UserID", "dbo.Users", "Id");
            AddForeignKey("dbo.TicketThreadMessages", "UserAuthorId", "dbo.Users", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.TicketThreadMessages", "UserAuthorId", "dbo.Users");
            DropForeignKey("dbo.Licenses", "UserID", "dbo.Users");
            DropForeignKey("dbo.Tickets", "LicenseId", "dbo.Licenses");
            DropForeignKey("dbo.Tickets", "HelpTopicId", "dbo.HelpTopics");
            DropForeignKey("dbo.TicketThreadMessages", "StaffAuthorId", "dbo.StaffMembers");
            DropForeignKey("dbo.TicketEventsHistories", "DoerId", "dbo.StaffMembers");
            DropForeignKey("dbo.StaffLogs", "StaffMemberId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "LastRespondentId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "EditorStaffId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "CreatorStaffId", "dbo.StaffMembers");
            DropForeignKey("dbo.Tickets", "AssignedStaffId", "dbo.StaffMembers");
            DropForeignKey("dbo.InternalNotes", "AuthorId", "dbo.StaffMembers");
            DropForeignKey("dbo.TicketThreadMessages", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.TicketEventsHistories", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.Tickets", "UserId", "dbo.Users");
            DropForeignKey("dbo.InternalNotes", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.Departments", "ManagerId", "dbo.StaffMembers");
            DropIndex("dbo.TicketThreadMessages", new[] { "UserAuthorId" });
            DropIndex("dbo.TicketThreadMessages", new[] { "StaffAuthorId" });
            DropIndex("dbo.TicketThreadMessages", new[] { "TicketId" });
            DropIndex("dbo.TicketEventsHistories", new[] { "DoerId" });
            DropIndex("dbo.TicketEventsHistories", new[] { "TicketId" });
            DropIndex("dbo.StaffLogs", new[] { "StaffMemberId" });
            DropIndex("dbo.Licenses", new[] { "UserID" });
            DropIndex("dbo.Tickets", new[] { "CreatorStaffId" });
            DropIndex("dbo.Tickets", new[] { "HelpTopicId" });
            DropIndex("dbo.Tickets", new[] { "EditorStaffId" });
            DropIndex("dbo.Tickets", new[] { "LastRespondentId" });
            DropIndex("dbo.Tickets", new[] { "AssignedStaffId" });
            DropIndex("dbo.Tickets", new[] { "LicenseId" });
            DropIndex("dbo.Tickets", new[] { "UserId" });
            DropIndex("dbo.InternalNotes", new[] { "AuthorId" });
            DropIndex("dbo.InternalNotes", new[] { "TicketId" });
            DropIndex("dbo.Departments", new[] { "ManagerId" });
            DropPrimaryKey("dbo.TMS_Settings");
            DropPrimaryKey("dbo.TicketThreadMessages");
            DropPrimaryKey("dbo.TicketEventsHistories");
            DropPrimaryKey("dbo.StaffLogs");
            DropPrimaryKey("dbo.StaffGroups");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Licenses");
            DropPrimaryKey("dbo.InternalNotes");
            DropPrimaryKey("dbo.HelpTopics");
            DropPrimaryKey("dbo.StaffMembers");
            DropPrimaryKey("dbo.Departments");
            AlterColumn("dbo.TMS_Settings", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TicketThreadMessages", "UserAuthorId", c => c.String(maxLength: 255));
            AlterColumn("dbo.TicketThreadMessages", "StaffAuthorId", c => c.String(maxLength: 255));
            AlterColumn("dbo.TicketThreadMessages", "TicketId", c => c.Guid(nullable: false));
            AlterColumn("dbo.TicketThreadMessages", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TicketEventsHistories", "DoerId", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.TicketEventsHistories", "TicketId", c => c.Guid(nullable: false));
            AlterColumn("dbo.TicketEventsHistories", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.StaffLogs", "StaffMemberId", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.StaffLogs", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.StaffGroups", "Id", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Users", "CustomerId", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Users", "SupervisorId", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Users", "Id", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Licenses", "UserID", c => c.String(maxLength: 255));
            AlterColumn("dbo.Licenses", "CustomerID", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Licenses", "Id", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Tickets", "CreatorStaffId", c => c.String(maxLength: 255));
            AlterColumn("dbo.Tickets", "HelpTopicId", c => c.String(maxLength: 255));
            AlterColumn("dbo.Tickets", "EditorStaffId", c => c.String(maxLength: 255));
            AlterColumn("dbo.Tickets", "LastRespondentId", c => c.String(maxLength: 255));
            AlterColumn("dbo.Tickets", "AssignedStaffId", c => c.String(maxLength: 255));
            AlterColumn("dbo.Tickets", "LicenseId", c => c.String(maxLength: 255));
            AlterColumn("dbo.Tickets", "UserId", c => c.String(maxLength: 255));
            AlterColumn("dbo.InternalNotes", "AuthorId", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.InternalNotes", "TicketId", c => c.Guid(nullable: false));
            AlterColumn("dbo.InternalNotes", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.HelpTopics", "Id", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.StaffMembers", "DepartmentId", c => c.String());
            AlterColumn("dbo.StaffMembers", "StaffGroupId", c => c.String());
            AlterColumn("dbo.StaffMembers", "Id", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Departments", "ManagerId", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Departments", "Id", c => c.String(nullable: false, maxLength: 255));
            AddPrimaryKey("dbo.TMS_Settings", "Id");
            AddPrimaryKey("dbo.TicketThreadMessages", "Id");
            AddPrimaryKey("dbo.TicketEventsHistories", "Id");
            AddPrimaryKey("dbo.StaffLogs", "Id");
            AddPrimaryKey("dbo.StaffGroups", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.Licenses", "Id");
            AddPrimaryKey("dbo.InternalNotes", "Id");
            AddPrimaryKey("dbo.HelpTopics", "Id");
            AddPrimaryKey("dbo.StaffMembers", "Id");
            AddPrimaryKey("dbo.Departments", "Id");
            CreateIndex("dbo.TicketThreadMessages", "UserAuthorId");
            CreateIndex("dbo.TicketThreadMessages", "StaffAuthorId");
            CreateIndex("dbo.TicketThreadMessages", "TicketId");
            CreateIndex("dbo.TicketEventsHistories", "DoerId");
            CreateIndex("dbo.TicketEventsHistories", "TicketId");
            CreateIndex("dbo.StaffLogs", "StaffMemberId");
            CreateIndex("dbo.Licenses", "UserID");
            CreateIndex("dbo.Tickets", "CreatorStaffId");
            CreateIndex("dbo.Tickets", "HelpTopicId");
            CreateIndex("dbo.Tickets", "EditorStaffId");
            CreateIndex("dbo.Tickets", "LastRespondentId");
            CreateIndex("dbo.Tickets", "AssignedStaffId");
            CreateIndex("dbo.Tickets", "LicenseId");
            CreateIndex("dbo.Tickets", "UserId");
            CreateIndex("dbo.InternalNotes", "AuthorId");
            CreateIndex("dbo.InternalNotes", "TicketId");
            CreateIndex("dbo.Departments", "ManagerId");
            AddForeignKey("dbo.TicketThreadMessages", "UserAuthorId", "dbo.Users", "Id");
            AddForeignKey("dbo.Licenses", "UserID", "dbo.Users", "Id");
            AddForeignKey("dbo.Tickets", "LicenseId", "dbo.Licenses", "Id");
            AddForeignKey("dbo.Tickets", "HelpTopicId", "dbo.HelpTopics", "Id");
            AddForeignKey("dbo.TicketThreadMessages", "StaffAuthorId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.TicketEventsHistories", "DoerId", "dbo.StaffMembers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StaffLogs", "StaffMemberId", "dbo.StaffMembers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tickets", "LastRespondentId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.Tickets", "EditorStaffId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.Tickets", "CreatorStaffId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.Tickets", "AssignedStaffId", "dbo.StaffMembers", "Id");
            AddForeignKey("dbo.InternalNotes", "AuthorId", "dbo.StaffMembers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TicketThreadMessages", "TicketId", "dbo.Tickets", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TicketEventsHistories", "TicketId", "dbo.Tickets", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tickets", "UserId", "dbo.Users", "Id");
            AddForeignKey("dbo.InternalNotes", "TicketId", "dbo.Tickets", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Departments", "ManagerId", "dbo.StaffMembers", "Id", cascadeDelete: true);
        }
    }
}
